services:
  pgsql:
    image: postgres:15.10-bookworm
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./pgsql/postgresql.conf:/etc/postgresql/postgresql.conf

  nginx:
    image: nginx:1.27.3-bookworm
    ports:
      - "8088:80"
      - "5555:5555"
    volumes:
      - ./html:/var/www/html
      - ./nginx/conf/conf.d:/etc/nginx/conf.d
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf

volumes:
  postgres_data:
